# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: dog_owner_development
  pool: 5
  username: vencarbon
  password: gfhfljrc

test:
  adapter: postgresql
  encoding: unicode
  database: dog_owner_test
  pool: 5
  username: vencarbon
  password: gfhfljrc

production:
  adapter: postgresql
  encoding: unicode
  database: dog_owner_production
  pool: 5
  username: vencarbon
  password: gfhfljrc
